# Generated by Django 2.1.4 on 2018-12-30 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medme', '0002_wallet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='customer',
        ),
        migrations.AddField(
            model_name='customer',
            name='wallet',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='medme.Wallet'),
        ),
    ]
