# Generated by Django 2.1.4 on 2019-01-01 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medme', '0003_auto_20181230_2217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='wallet',
        ),
        migrations.AddField(
            model_name='wallet',
            name='customer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='medme.Customer'),
            preserve_default=False,
        ),
    ]
